name: Link Check

on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Run linkinator against traceremove.dev
        run: npx --yes linkinator https://traceremove.dev/ --recurse --format csv --skip "https://scholar\\.google\\.com/.*|https://philpeople\\.org/.*" | tee linkinator.csv

      - name: Upload linkinator.csv artifact
        uses: actions/upload-artifact@v4
        with:
          name: linkinator-report
          path: linkinator.csv
